create table player(
	id BIGSERIAL PRIMARY KEY NOT NULL,
    player_id varchar(255) NOT NULL UNIQUE,
    birth_date date,
    birth_country varchar(255),
    birth_state varchar(255),
    birth_city varchar(255),
    death_date varchar(255),
    death_country varchar(255),
    death_state varchar(255),
    death_city varchar(255),
	first_name varchar(255),
	last_name varchar(255),
	given_name varchar(255),
    weight int,
    height int,
    bats varchar(255),
    throws_hand varchar(255),
    debut date,
    final_game date,
    retro_id varchar(255),
    bbref_id varchar(255),
	create_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_DATE,
	modify_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_DATE);
